WebUI/Controllers/CartController.cs
using System.Linq;
using System.Web.Mvc;
using Domain.Entities;
using WebUI.Models;
using Domain.Abstract;

namespace WebUI.Controllers
{
    
    public class CartController : Controller
    {
        private IItemRepository repository;
        private IOrderProcessor orderProcessor;
        public CartController(IItemRepository repo, IOrderProcessor processor)
        {
            repository = repo;
            orderProcessor = processor;
        }

        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }

        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Извините, ваша корзина пуста!");
            }

            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(shippingDetails);
            }
        }




        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public RedirectToRouteResult AddToCart(Cart cart, int itemId, string returnUrl)
        {
            Item item = repository.Items
                .FirstOrDefault(g => g.ItemId == itemId);

            if (item != null)
            {
                cart.AddItem(item, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int itemId, string returnUrl)
        {
            Item item = repository.Items
                .FirstOrDefault(g => g.ItemId == itemId);

            if (item != null)
            {
                cart.RemoveLine(item);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }
        
    }
}

WebUI/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Abstract;
using Domain.Entities;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class ItemController : Controller
    {
        private IItemRepository repository;
        public int pageSize = 4;

        public ItemController(IItemRepository repo)
        {
            repository = repo;
        }

        public ViewResult List(string category, int page = 1)
        {
            ItemsListViewModel model = new ItemsListViewModel
            {
                Items = repository.Items
                    .Where(p => category == null || p.Category == category)
                    .OrderBy(item => item.ItemId)
                    .Skip((page - 1) * pageSize)
                    .Take(pageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = category == null ?
                repository.Items.Count() :
                repository.Items.Where(item => item.Category == category).Count()
                },
                CurrentCategory = category
            };
            return View(model);
        }
        public FileContentResult GetImage(int itemId)
        {
            Item item = repository.Items
                .FirstOrDefault(g => g.ItemId == itemId);

            if (item != null)
            {
                return File(item.ImageData, item.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

WebUI/Controllers/NavController.cs
using Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers
{
    public class NavController : Controller
    {
        private IItemRepository repository;

        public NavController(IItemRepository repo)
        {
            repository = repo;
        }

        public PartialViewResult Menu(string category = null, bool horizontalNav = false)
        {
            ViewBag.SelectedCategory = category;

            IEnumerable<string> categories = repository.Items
                .Select(game => game.Category)
                .Distinct()
                .OrderBy(x => x);

            string viewName = horizontalNav ? "MenuHorizontal" : "Menu";
            return PartialView(viewName, categories);
        }
    }
}

WebUI/Views/Shared/ItemSummary.cshtml
@model Domain.Entities.Item

    <div style="background-image: url('../../Images/gold_creep.png') ;background-position: right; background-size: contain;  background-repeat: no-repeat" class="hidden-xs well">
        @if (Model.ImageData != null)
        {
            <div  class="pull-left" style="margin-right: 10px">
                <img class="img-thumbnail" width="75" height="75"
                     src="@Url.Action("GetImage", "Item",
                new { Model.ItemId })" />
            </div>
        }
        <h3>
            <h3>
                <strong>@Model.Name</strong>
                <span class="pull-right label label-primary">@Model.Price.ToString("# руб")</span>
            </h3>

            @using (Html.BeginForm("AddToCart", "Cart"))
            {
                <div class="pull-right">
                    @Html.HiddenFor(x => x.ItemId)
                    @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                    <input type="submit" class="btn btn-success" value="Добавить" />
                </div>
            }
            <p class="lead" style="color:black; font: bold 24px trojan; text-align: justify">@Model.Description</p>


        </h3>

    </div>
    <div class="visible-xs well">
        @if (Model.ImageData != null)
        {
            <div class="pull-left" style="margin-right: 10px">
                <img class="img-thumbnail" width="75" height="75"
                     src="@Url.Action("GetImage", "Item",
                new { Model.ItemId })" />
            </div>
        }
        <h3>
            <h3>
                <strong>@Model.Name</strong>
                <span class="pull-right label label-primary">@Model.Price.ToString("# руб")</span>
            </h3>

            @using (Html.BeginForm("AddToCart", "Cart"))
            {
                <div class="pull-right">
                    @Html.HiddenFor(x => x.ItemId)
                    @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                    <input type="submit" class="btn btn-success" value="Добавить" />
                </div>
            }
            <p class="lead" style="color:black; font: bold 24px trojan; text-align: justify; margin-right:0px; margin-top:55px">@Model.Description</p>


        </h3>

    </div>

WebUI/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.9.1.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <title></title>
</head>
<body>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
    <style>
        .navbar-right {
            float: right !important;
            margin-right: 15px;
            margin-left: 15px;
        }
    </style>
</head>
<body style="background-image: url('../../Images/Wiki-background.jpg');background-position: center" class="row panel">
    <div style="background-image: url('../../Images/background.png');background-position: center" class="navbar navbar-inverse center-block" role="navigation">

        <a class="navbar-brand" href="#" style="color: white; font: bold 25px arial;" ;>
            <span class="hidden-xs"> @Html.ActionLink("DotaStore - магазин лесных предметов Dota 2!", "List", "Item", new { Style = "color: white; font: bold 25px arial;" })</span>
            
            

        </a>
        @Html.Action("Summary", "Cart")
    </div>
    <div class="visible-xs">
        @Html.Action("Menu", "Nav", new { horizontalNav = true })
    </div>

    <div style="background-image: url('../../Images/Wiki-background.jpg');background-position: center" class="row panel">
        <div  id="categories" class="col-sm-3 hidden-xs">
            @Html.Action("Menu", "Nav")
        </div>
        <div   class="col-xs-12 col-sm-8">
            @RenderBody()
        </div>
    </div>
  
</body>
</html>